// Generated by CoffeeScript 1.6.3
(function() {
  var last_msg_count, last_visitor, processInformation, profile_db, pullInformation, refreshStore, sendDesktopNotification;

  last_msg_count = null;

  last_visitor = null;

  profile_db = {};

  sendDesktopNotification = function(title, message, image) {
    if (image == null) {
      image = null;
    }
    return chrome.extension.sendRequest({
      'msg': message,
      'title': title,
      'image': image
    });
  };

  processInformation = function(data) {
    var from, highest_date, image, img, profile, time, visitor, _i, _len, _ref, _ref1;
    if (data.msgcenter) {
      if (data.msgcenter.num_mails_new > 0 && data.msgcenter.num_mails_new !== last_msg_count) {
        sendDesktopNotification('Neue Finya-Nachrichten', data.msgcenter.num_mails_new + ' neue Nachrichten');
        chrome.storage.sync.set({
          'last_msg_count': data.msgcenter.num_mails_new
        });
      } else {
        chrome.storage.sync.set({
          'last_msg_count': 0
        });
      }
    }
    if (data.visits && data.visits.count > 0) {
      highest_date = last_visitor;
      _ref = data.visits.data;
      for (time in _ref) {
        visitor = _ref[time];
        if (visitor.ts > last_visitor) {
          image = null;
          from = '';
          if (profile_db[visitor.id]) {
            img = profile_db[visitor.id].picture;
            image = "http://static.finya.net/img/u/" + img[0] + "/" + img[1] + "/" + img + "_11.jpg";
            from = " aus " + profile_db[visitor.id].city;
          }
          sendDesktopNotification('Neuer Finya-Besucher', "" + visitor.ts_c + ": " + visitor.nickname + ", " + visitor.age + " Jahre" + from, image);
          if (visitor.ts > highest_date) {
            highest_date = visitor.ts;
          }
        }
      }
      chrome.storage.sync.set({
        'last_visitor': highest_date
      });
    }
    if (data.online) {
      _ref1 = data.online.data;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        profile = _ref1[_i];
        profile_db[profile.id] = {
          'city': profile.home_city,
          'nickname': profile.nickname,
          'picture': profile.id_pic
        };
      }
      return chrome.storage.local.set({
        'profiledb': profile_db
      });
    }
  };

  pullInformation = function() {
    return $.post('http://www.finya.de/MyFinya/refreshUI/?c=vis,msc,onl', processInformation, 'JSON');
  };

  refreshStore = function() {
    chrome.storage.sync.get('last_msg_count', function(data) {
      if (data.last_msg_count) {
        return last_msg_count = data.last_msg_count;
      } else {
        return last_msg_count = 0;
      }
    });
    chrome.storage.sync.get('last_visitor', function(data) {
      if (data.last_visitor) {
        return last_visitor = data.last_visitor;
      } else {
        return last_visitor = 0;
      }
    });
    return chrome.storage.local.get('profiledb', function(data) {
      if (data.profiledb) {
        return profile_db = data.profiledb;
      }
    });
  };

  $(function() {
    refreshStore();
    chrome.storage.onChanged.addListener(function(changes, namespace) {
      var key, value, _results;
      _results = [];
      for (key in changes) {
        value = changes[key];
        if (key === 'last_msg_count') {
          if (value.newValue) {
            last_msg_count = value.newValue;
          } else {
            last_msg_count = 0;
          }
        }
        if (key === 'last_visitor') {
          if (value.newValue) {
            _results.push(last_visitor = value.newValue);
          } else {
            _results.push(last_visitor = 0);
          }
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
    return setInterval(pullInformation, 20000);
  });

}).call(this);
